choco upgrade googlechrome -fy
choco upgrade visualstudio2019enterprise -fy
choco upgrade vscode -fy
choco upgrade sql-server-management-studio -fy
choco upgrade robo3t -fy
choco upgrade postman -fy
choco upgrade insomnia-rest-api-client -fy
choco upgrade bloomrpc -fy
choco upgrade servicebusexplorer -fy
choco upgrade microsoftazurestorageexplorer -fy
choco upgrade microsoft-windows-terminal -fy
choco upgrade slack -fy
choco upgrade microsoft-teams -fy
choco upgrade discord -fy
choco upgrade skype -fy
choco upgrade awscli -fy
choco upgrade azure-cli -fy
choco upgrade minikube -fy
choco upgrade kubernetes-cli -fy
choco upgrade istioctl -fy
choco upgrade kubernetes-helm -fy
choco upgrade terraform -fy
choco upgrade pgadmin4 -fy